/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./index.ts", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        elevated: "var(--color-elevated)",
        ink: "var(--color-ink)",
        muted: "var(--color-muted)",
        accent: "var(--color-accent)",
        "accent-soft": "var(--color-accent-soft)",
        border: "var(--color-border)",
        success: "var(--color-success)",
        "success-muted": "var(--color-success-muted)",
        warning: "var(--color-warning)",
        "warning-muted": "var(--color-warning-muted)",
        danger: "var(--color-danger)",
        "danger-muted": "var(--color-danger-muted)",
        neutral: "var(--color-neutral)",
        white: "var(--color-white)",
      },
      spacing: {
        xxs: 4,
        xs: 8,
        sm: 12,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 40,
      },
      borderRadius: {
        sm: 8,
        md: 12,
        lg: 16,
      },
      fontSize: {
        display: ["28px", { lineHeight: "34px", fontWeight: "600" }],
        title: ["28px", { lineHeight: "34px", fontWeight: "600" }],
        heading: ["20px", { lineHeight: "26px", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px" }],
        caption: ["14px", { lineHeight: "20px" }],
        numeral: ["22px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
